apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-05-10T04:44:39Z"
  generation: 1
  labels:
    app: simple01-web
    chart: simple01-1.0.0
    release: simple01
    version: 1.0.0
  name: simple01-web
  namespace: millet
  resourceVersion: "161904"
  selfLink: /apis/extensions/v1beta1/namespaces/millet/deployments/simple01-web
  uid: 51f87c42-72de-11e9-b0af-5ef9efd9374c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: simple01-web
      chart: simple01-1.0.0
      release: simple01
      version: 1.0.0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple01-web
        chart: simple01-1.0.0
        release: simple01
        version: 1.0.0
    spec:
      affinity: {}
      containers:
      - env:
        - name: spring.profiles.active
          value: dev
        - name: target.was.service.name
          value: simple01-was
        envFrom:
        - configMapRef:
            name: demo-config
        image: neocode24/web-sample:1.0.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: web
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2019-05-10T04:44:39Z"
    lastUpdateTime: "2019-05-10T04:44:39Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2019-05-10T04:44:39Z"
    lastUpdateTime: "2019-05-10T04:44:39Z"
    message: ReplicaSet "simple01-web-d7f9f867d" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
