version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    environment:
     - POSTGRES_DB=helm_sample
     - POSTGRES_USER=helm_user
     - POSTGRES_PASSWORD=new1234!
     - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
     - "5432:5432"
    volumes:
      - "data:/var/lib/postgresql/data"
      # - ./data/data.sql:/docker-entrypoint-initdb.d/init.sql
 
volumes:
  data:
    external: true


