version: '3'
services:
  web-sample:
    image: helm-sample/web-sample:1.0.0
    environment:
      target.was.service.name: was-sample:8080
    ports:
     - "8080:8080"
    links:
     - was-sample

  was-sample:
    image: helm-sample/was-sample:1.0.0
    environment:
      target.db.service.name: db-sample:8080
    links:
     - cache-sample

  db-sample:
    image: helm-sample/db-sample:1.0.0
    environment:
      target.cache.service.name: cache-sample:8080
      POSTGRES_ENV_IP: postgres
      POSTGRES_ENV_PORT: 5432
      POSTGRES_ENV_DB: helm_sample
    links:
     - postgres 

  cache-sample:
    image: helm-sample/cache-sample:1.0.0
    environment: 
      spring.redis.host: redis
      spring.redis.port: 6379
    links:
     - redis

  redis:
    image: "redis:latest"

  postgres:
    image: postgres
    environment:
     - POSTGRES_DB=helm_sample
     - POSTGRES_USER=helm_user
     - POSTGRES_PASSWORD=new1234!
     - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - "~/data:/var/lib/postgresql/data"
      # - ./data/data.sql:/docker-entrypoint-initdb.d/init.sql
 
        #volumes:
        #  data:
        #    external: true


