apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: simple02-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "simple02-package.container.ipc.kt.com"
      #    tls:
      #      httpsRedirect: true
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    hosts:
    - "simple02-package.container.ipc.kt.com"
    tls:
      mode: SIMPLE
