{{- $releaseName := .Release.Name -}}
{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ .name }}
  labels:
    appName: {{ $releaseName }}
    svcName: {{ $releaseName }}-{{ .name }}
    version: {{ .tag }}
    chart: {{ template "complex02.chart" $ }}
    release: {{ $releaseName }}
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    appName: {{ $releaseName }}
    svcName: {{ $releaseName }}-{{ .name }}
    version: {{ .tag }}
    chart: {{ template "complex02.chart" $ }}
    release: {{ $releaseName }}
---

{{- end }}
