{{- if .Values.istio.enabled -}}
{{- $releaseName := .Release.Name -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $releaseName }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range .Values.ingress.hosts }}
    - {{ . }} 
    {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $releaseName }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ $releaseName }}-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: {{ .Values.istio.destination.host }}
        subset: v2
      weight: {{ .Values.istio.destination.v2.weight }}
    - destination:
        host: {{ .Values.istio.destination.host }}
        subset: v1
      weight: {{ .Values.istio.destination.v1.weight }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $releaseName }}
spec:
  host: {{ .Values.istio.destination.host }}
  subsets:
  - name: v2
    labels:
      version: {{ .Values.istio.destination.v2.version }}
  - name: v1
    labels:
      version: {{ .Values.istio.destination.v1.version }}
{{- end }}
