# Default values for postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ktis-bastion01.container.ipc.kt.com:5000/admin/postgres
  tag: 10.6
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5432
  targetPort: 5432

dev:
  enabled: true
  POSTGRES_DB: helm_sample
  POSTGRES_USER: helm_user
  POSTGRES_PASSWORD: new1234!
  POSTGRES_INITDB_ARGS: --encoding=UTF-8

stage:
  enabled: false
  POSTGRES_DB: helm_sample
  POSTGRES_USER: helm_user
  POSTGRES_PASSWORD: new1234!
  POSTGRES_INITDB_ARGS: --encoding=UTF-8

production:
  enabled: false
  POSTGRES_DB: helm_sample
  POSTGRES_USER: helm_user
  POSTGRES_PASSWORD: new1234!
  POSTGRES_INITDB_ARGS: --encoding=UTF-8

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
