{{- $releaseName := .Release.Name -}}
{{- range.Values.batches }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "simple05.fullname" $ }}-{{ .name }}
  labels:
    app: {{ template "simple05.name" $ }}-{{ .name }}-{{ .image.tag }}
    chart: {{ template "simple05.chart" $ }}
    release: {{ $releaseName }}
spec:
  schedule: {{ quote .schedule }}
  failedJobsHistoryLimit:  {{ .failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  jobTemplate:
    metadata:
      labels:
        app: {{ .name }}-{{ .image.tag }}
        chart: {{ template "simple05.chart" $ }}
        release: {{ $releaseName }}
    spec:
      template:
        metadata:
          labels:
            app: {{ .name }}-{{ .image.tag }}
            chart: {{ template "simple05.chart" $ }}
            release: {{ $releaseName }}
        spec:
          containers:
          - name: {{ .name }}
            image:  "{{ .image.repository }}:{{ .image.tag }}"
            imagePullPolicy: {{ .image.pullPolicy }}

            {{- range $k, $v := .env }}
              {{- if .enabled }}
            env:
                {{- range $i, $j := . }}
                  {{- if ne $i "enabled" }}
              - name: {{ $i }}
                value: {{ quote $j | default "" }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
          restartPolicy: {{ .restartPolicy }}
---

{{- end }}
