{{- $releaseName := .Release.Name -}}
{{- range.Values.batches }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $releaseName }}-{{ .name }}
  labels:
    appName: {{ $releaseName }}
    svcName: {{ $releaseName }}-{{ .name }}
    version: {{ .image.tag }}
    chart: {{ template "simple05.chart" $ }}
    release: {{ $releaseName }}
spec:
  schedule: {{ quote .schedule }}
  failedJobsHistoryLimit:  {{ .failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  jobTemplate:
    metadata:
      labels:
        appName: {{ $releaseName }}
        svcName: {{ $releaseName }}-{{ .name }}
        version: {{ .image.tag }}
        chart: {{ template "simple05.chart" $ }}
        release: {{ $releaseName }}
    spec:
      template:
        metadata:
          labels:
            appName: {{ $releaseName }}
            svcName: {{ $releaseName }}-{{ .name }}
            version: {{ .image.tag }}
            chart: {{ template "simple05.chart" $ }}
            release: {{ $releaseName }}
        spec:
          containers:
          - name: {{ .name }}
            image:  "{{ .image.repository }}:{{ .image.tag }}"
            imagePullPolicy: {{ .image.pullPolicy }}
            args: {{ .args }}

            {{- range $k, $v := .env }}
              {{- if .enabled }}
            env:
                {{- range $i, $j := . }}
                  {{- if ne $i "enabled" }}
              - name: {{ $i }}
                value: {{ quote $j | default "" }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
          restartPolicy: {{ .restartPolicy }}
---

{{- end }}
