{{- $releaseName := .Release.Name -}}
{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "simple04.fullname" $ }}-{{ .name }}
  labels:
    app: {{ template "simple04.name" $ }}-{{ .name }}-{{ .tag }}
    chart: {{ template "simple04.chart" $ }}
    release: {{ $releaseName }}
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .name }}-{{ .tag }}
    chart: {{ template "simple04.chart" $ }}
    release: {{ $releaseName }}
---

{{- end }}
